### ISSUE TITLE
[Security] Exposed password

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [Moesif/moesif-nodejs#37]
I am making a request where the response has the property `password`.

`moesif-nodejs - v2.9.19`

**Postman screenshot**
![image](https://user-images.githubusercontent.com/29241659/92280638-38191e80-eed0-11ea-99ca-b4ac4b2dffef.png)

On the moesif page, a different value is displayed in `password`, which seems to correspond to some password that I could not identify from where it is (I authenticate using GitHub).

**Moesif.com screenshot**
![image](https://user-images.githubusercontent.com/29241659/92280688-5ed75500-eed0-11ea-9639-b9cc353147ea.png)

**Comment by dgilling** [comment]
We automatically hash passwords for security based on the logic here: https://github.com/Moesif/moesif-nodejs/blob/dabbc38a0d441815248131324bea4c04a90e3583/lib/dataUtils.js#L40 <https://github.com/Moesif/moesif-nodejs/blob/dabbc38a0d441815248131324bea4c04a90e3583/lib/dataUtils.js#L40>
Curious if there was a need to log the raw passwords? If so, you can set this option to true:

applicationId: 'XXX',
noAutoHideSensitive <https://github.com/Moesif/moesif-nodejs/blob/71b5e26c749b81df7eeb80b43931705f8817ce4f/README.md#noautohidesensitive>: true

Derric

**Comment by PauloGoncalvesBH** [comment]
I was not so clear, sorry.

I thought the problem was a password leak, but from what I understand now it's just that the information is being displayed wrong on the moesif.com dashboard.

It should be `"password": "password é obrigatório"` and it was `"password": "3fasdasdasdasde0"`.

**Comment by dgilling** [comment]
No worries and always good to check on these things ;)
