### ISSUE TITLE
This module can only be referenced with ECMAScript imports/exports

### ISSUE THREAD

**Issue by aarajput** [Moesif/moesif-nodejs#72]
**This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.**

I am getting this error when i tried to import it into my typescript nodejs project.

import * as moesif from 'moesif-nodejs';

**Comment by xinghengwang** [comment]
ok. can you try to turn on esModuleInterop? 
We'll see what the solution is. thanks.
